# Generated by Django 4.0.6 on 2022-07-14 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_origem', models.IntegerField()),
                ('conta_destino', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=datetime.date(2022, 7, 14))),
            ],
        ),
    ]
