# Generated by Django 4.0.6 on 2022-07-14 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=200)),
                ("saldo", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conta_origem", models.IntegerField()),
                ("conta_destino", models.IntegerField()),
                ("valor", models.FloatField()),
                (
                    "data_transacao",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
            ],
        ),
    ]
