# Generated by Django 4.0.6 on 2022-07-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='data',
            new_name='data_transacao',
        ),
    ]
